spring:
  application:
    name: mi-aplicacion

  datasource:
    url: jdbc:postgresql://localhost:5432/novabank
    username: banco_user
    password: 1234
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop # Cambiar a validate en producción
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080

jwt:
  secret: clave_super_secreta_de_minimo_32_caracteres
  expiration: 86400000

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs
